name: Deploy pages
on: 
  push:
    branches: [master]
permissions: :
  pages: write
  id-token: write
jobs:
  deploy:
   runs-on: ubuntu-latest
   environment: github-pages
   steps:
     -user: actions/checkout@v4
     -uses: action/upload-pages-artifact@v3
     with:
       path: 
     -uses: action/deploy-pages@v4
   
